INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "PACS"
  SOURCE_DOMAINS: ["art_painting"]
  # SOURCE_DOMAINS: ["cartoon"]
  # SOURCE_DOMAINS: ["photo"]
  # SOURCE_DOMAINS: ["sketch"]
  TARGET_DOMAINS: ["cartoon"]
  # TARGET_DOMAINS: ["photo"]
  # TARGET_DOMAINS: ["sketch"]
  # TARGET_DOMAINS: ["art_painting"]
# you can modify the code to explore four domains

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
